version: '3.1'
services:
  server1:
    image: vivekbhandari/mfp_server:7
    tty: true
    hostname: server1
    networks: 
      - mynet123
  server2:
    image: vivekbhandari/mfp_server:7
    tty: true
    hostname: server2
    networks: 
      - mynet123
  haproxy1:
    image: haproxy:1.7
    ports:
      - "80:80"
    volumes:
      - ./host_volume/haproxy1/:/usr/local/etc/haproxy:ro
    networks: 
      - mynet123
  mysql1:
    image: mysql/mysql-server
    volumes:
      - ./host_volume/mysql1:/var/lib/mysql
      - ./mysqlinit:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: mfp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynet123
  zookeeper1:
    image: zookeeper
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888
    networks: 
      - mynet123
  zookeeper2:
    image: zookeeper
    hostname: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888
    networks: 
      - mynet123
  kafka1:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
    environment:
      KAFKA_ADVERTISED_LISTENERS: kafka1
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "chat_events:3:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:3181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet123
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
    environment:
      KAFKA_ADVERTISED_LISTENERS: kafka2
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:3181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet123
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    depends_on:
      - zookeeper1
      - zookeeper2
    environment:
      KAFKA_ADVERTISED_LISTENERS: kafka3
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:3181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - mynet123

networks:
    mynet123:
        driver: bridge
